### PR TITLE
Bug 1171508 - fix bugs in BitmapData#clone

### PR DESCRIPTION
**Pull request by tschneidereit**
Making it work for `remoteDirty` instances and actually clone the buffer instead of having both instances share the same buffer. r=mbx

[Review on Reviewable](https://reviewable.io/reviews/mozilla/shumway/2273)

### CODE REVIEW

**Comment by tschneidereit** [comment]
@mbebenita: review ping

**Comment by tschneidereit** [comment]
Shifting review to @tobytailor.

**Comment by tobytailor** [comment]
Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2273)

**Pull request merged**
