### PR TITLE
Implement or stub as somewhatImplemented most of the 2.5D transforms-related AS3 API surface

### PR DESCRIPTION
**Pull request by tschneidereit**
This should eliminate most of the remaining notImplemented errors we get when running our reports on ads.

[Review on Reviewable](https://reviewable.io/reviews/mozilla/shumway/2302)

### CODE REVIEW

**Comment by tobytailor** [comment]
Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[src/flash/geom/PerspectiveProjection.ts, line 28 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2302#-Jt0JhvvVFq-cRU8T_ci)** ([raw file](https://github.com/mozilla/shumway/blob/4a639f60bb8afc2b857cdd18a243cf8642c5ee86/src/flash/geom/PerspectiveProjection.ts#L28)):</sup>
All these numbers look magical to me, please add a comment explaining where they come from.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2302)

**Comment by tschneidereit** [comment]
Review status: 17 of 25 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[src/flash/geom/PerspectiveProjection.ts, line 28 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2302#-Jt0JhvvVFq-cRU8T_ci)** ([raw file](https://github.com/mozilla/shumway/blob/4a639f60bb8afc2b857cdd18a243cf8642c5ee86/src/flash/geom/PerspectiveProjection.ts#L28)):</sup>
Right you are! What's more, in an attempt to more fully understand what the values should really be set to, I completely changed how `PerspectiveProjection` interacts with `DisplayObject`s. See the commit message for the latest commit in this PR.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2302)

**Comment by yurydelendik** [comment]
> Trace tests: FAILED

The trace file for the stas test must be updated.

> AVM2 ATS tests: FAILED

Ignore, #2350 is pending

**Comment by tschneidereit** [comment]
> The trace file for the stas test must be updated.

I did update it. There are, quite surprisingly, rounding differences between what happens on my machine and on botio. Will add a `toFixed`.

**Comment by tobytailor** [comment]
Reviewed 1 of 8 files at r2.
Review status: 18 of 25 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2302)

**Comment by tobytailor** [comment]
<sup>**[src/flash/geom/PerspectiveProjection.ts, line 24 \[r3\]](https://reviewable.io:443/reviews/mozilla/shumway/2302#-JxkAWP8ET2YQVXMe9Th)** ([raw file](https://github.com/mozilla/shumway/blob/eb41d8792e5562cdc20949fc2a9fec2c28f20c96/src/flash/geom/PerspectiveProjection.ts#L24)):</sup>
Better, but still don't know where these numbers come from. Nit.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2302)

**Comment by tobytailor** [comment]
Reviewed 4 of 8 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2302)

**Comment by tschneidereit** [comment]
Review status: 24 of 25 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[src/flash/geom/PerspectiveProjection.ts, line 24 \[r3\]](https://reviewable.io:443/reviews/mozilla/shumway/2302#-JxkAWP8ET2YQVXMe9Th)** ([raw file](https://github.com/mozilla/shumway/blob/eb41d8792e5562cdc20949fc2a9fec2c28f20c96/src/flash/geom/PerspectiveProjection.ts#L24)):</sup>
Ok, fixed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2302)

**Comment by tobytailor** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2302)

**Comment by tobytailor** [comment]
r+

**Pull request merged**
