### PR TITLE
Log startup timings

### PR DESCRIPTION
**Pull request by tschneidereit**
Logs the duration of two initialization phases: from startup triggering to player start and from player start to entering of the main loop.

@yurydelendik, I couldn't find a better way of funneling the startup timestamp through. If you see one, please tell me. Otherwise: r?

### CODE REVIEW

**Comment by yurydelendik** [comment]
>  I couldn't find a better way of funneling the startup timestamp through. 

Could you add this time to the "flashParams" (it's a bad name -- we probably need to change that to "playerStartupParameters" or something) for the extension?

**Comment by tschneidereit** [comment]
> Could you add this time to the "flashParams" (it's a bad name -- we probably need to change that to "playerStartupParameters" or something) for the extension?

Good call, done.

**Comment by yurydelendik** [comment]
r+

**Pull request merged**
