### PR TITLE
Bug 1136763: Fix name handling in AVM1 MovieClip methods. r=yury

### PR DESCRIPTION
**Pull request by tschneidereit**
[Review on Reviewable](https://reviewable.io/reviews/mozilla/shumway/2291)

### CODE REVIEW

**Comment by yurydelendik** [comment]
Looks good with examples what it fixes. For any AVM1 change the swfdec tests shall be run.

/botio test

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2291)

**Comment by tschneidereit** [comment]
> Looks good with examples what it fixes.

Right, I should've added a test. Fixed now.

> For any AVM1 change the swfdec tests shall be run.

I did that locally, which of course you couldn't know.

---

Review status: 2 of 6 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2291)

**Pull request merged**
