### PR TITLE
Adds jsplugins support to the extension.

### PR DESCRIPTION
**Pull request by yurydelendik**
in support of https://bugzilla.mozilla.org/show_bug.cgi?id=558184, additional configuration (in about:config): `shumway.disabled`=true

[Review on Reviewable](https://reviewable.io/reviews/mozilla/shumway/2294)

### CODE REVIEW

**Comment by tschneidereit** [comment]
Looks good to me. I added a few comments, but by and large this seems fine. I'm assuming that the moved functions, e.g. `isStandardEmbedWrapper`, haven't been modified internally, so didn't carefully review them.

---

Reviewed 2 of 4 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[extension/firefox/chrome/content.html, line 3 \[r2\]](https://reviewable.io:443/reviews/mozilla/shumway/2294#-JtSmUUIX3Xalci8vOdI)** ([raw file](https://github.com/mozilla/shumway/blob/7155300f6e2275b836db994a5944a9ef6da03b16/extension/firefox/chrome/content.html#L3)):</sup>
Uber-nit: might as well make this 2015.

---

<sup>**[extension/firefox/chrome/content.js, line 22 \[r2\]](https://reviewable.io:443/reviews/mozilla/shumway/2294#-JtSmiyxGMslAkfsfjtp)** ([raw file](https://github.com/mozilla/shumway/blob/7155300f6e2275b836db994a5944a9ef6da03b16/extension/firefox/chrome/content.js#L22)):</sup>
`winmm` is a little too short and unreadable for my taste. `windowMsgManager` would perhaps be a good compromise?

---

<sup>**[extension/firefox/chrome/content.js, line 23 \[r2\]](https://reviewable.io:443/reviews/mozilla/shumway/2294#-JtSn8ZEunjtVhy2E4bI)** ([raw file](https://github.com/mozilla/shumway/blob/7155300f6e2275b836db994a5944a9ef6da03b16/extension/firefox/chrome/content.js#L23)):</sup>
Please add a comment explaining what this does. It's entirely unclear to me why this condition would ever be the case, and why it's needed.

---

<sup>**[extension/firefox/chrome/plugin.js, line 79 \[r2\]](https://reviewable.io:443/reviews/mozilla/shumway/2294#-JtSnvo8bqDgnvKZBv2m)** ([raw file](https://github.com/mozilla/shumway/blob/7155300f6e2275b836db994a5944a9ef6da03b16/extension/firefox/chrome/plugin.js#L79)):</sup>
Why is this commented out? Should it be active? If so, please add an explanatory comment for why it's disabled. If not, remove it.

---

<sup>**[extension/firefox/content/ShumwayStreamConverter.jsm, line 265 \[r2\]](https://reviewable.io:443/reviews/mozilla/shumway/2294#-JtSp229JF99R6eb1VWN)** ([raw file](https://github.com/mozilla/shumway/blob/7155300f6e2275b836db994a5944a9ef6da03b16/extension/firefox/content/ShumwayStreamConverter.jsm#L265)):</sup>
Do we need this parameter at all, anymore? If not, remove it or at least add a TODO comment for the removal. If yes, add a comment explaining why it's hard-coded to `false` right now.

---

<sup>**[extension/firefox/content/ShumwayStreamConverter.jsm, line 267 \[r2\]](https://reviewable.io:443/reviews/mozilla/shumway/2294#-JtSpF6OHeAKZvZm4hVe)** ([raw file](https://github.com/mozilla/shumway/blob/7155300f6e2275b836db994a5944a9ef6da03b16/extension/firefox/content/ShumwayStreamConverter.jsm#L267)):</sup>
Same as above.

---

<sup>**[extension/firefox/content/ShumwayStreamConverter.jsm, line 270 \[r2\]](https://reviewable.io:443/reviews/mozilla/shumway/2294#-JtSpGU15gZTDKouuSes)** ([raw file](https://github.com/mozilla/shumway/blob/7155300f6e2275b836db994a5944a9ef6da03b16/extension/firefox/content/ShumwayStreamConverter.jsm#L270)):</sup>
Same as above.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2294)

**Comment by yurydelendik** [comment]
Review status: 1 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[extension/firefox/content/ShumwayStreamConverter.jsm, line 265 \[r2\]](https://reviewable.io:443/reviews/mozilla/shumway/2294#-JtSp229JF99R6eb1VWN)** ([raw file](https://github.com/mozilla/shumway/blob/7155300f6e2275b836db994a5944a9ef6da03b16/extension/firefox/content/ShumwayStreamConverter.jsm#L265)):</sup>
added comment above

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2294)

**Pull request merged**
