### PR TITLE
Misc textfield fixes.

### PR DESCRIPTION
**Pull request by tobytailor**
[Review on Reviewable](https://reviewable.io/reviews/mozilla/shumway/2327)

### CODE REVIEW

**Comment by yurydelendik** [comment]
"exec:test_swf" fails with:

```
< HASHCODE: test/swf/main.swf: 0xc4443936

---

> HASHCODE: test/swf/main.swf: 0x45e3b136
```

Looks like main movie hash changed (if it's expected modify baseline file)

/botio test

---

Reviewed 2 of 4 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2327)

**Comment by tobytailor** [comment]
@yurydelendik do we still have intentions to land this?

**Pull request merged**
