### PR TITLE
Improve the conformance of our navigateTo securityChecks, and support "javscript:" URLs

### PR DESCRIPTION
**Pull request by tschneidereit**
r? @yurydelendik

[Review on Reviewable](https://reviewable.io/reviews/mozilla/shumway/2349)

### CODE REVIEW

**Comment by yurydelendik** [comment]
Good to go with the fixes.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[extension/firefox/chrome/ShumwayCom.jsm, line 574 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2349#-JxgH9E3wUS9NLg_5DBZ)** ([raw file](https://github.com/mozilla/shumway/blob/b27e1676b6cd0ba6dad60089c15189a00f9b3467/extension/firefox/chrome/ShumwayCom.jsm#L574)):</sup>
`var scheme = Services.io.newURI(url).protocol;`?

---

<sup>**[extension/firefox/chrome/ShumwayCom.jsm, line 575 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2349#-JxgH7A3UPLKRnMTw_iG)** ([raw file](https://github.com/mozilla/shumway/blob/b27e1676b6cd0ba6dad60089c15189a00f9b3467/extension/firefox/chrome/ShumwayCom.jsm#L575)):</sup>
switch (scheme)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2349)

**Comment by tschneidereit** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[extension/firefox/chrome/ShumwayCom.jsm, line 574 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2349#-JxgH9E3wUS9NLg_5DBZ)** ([raw file](https://github.com/mozilla/shumway/blob/b27e1676b6cd0ba6dad60089c15189a00f9b3467/extension/firefox/chrome/ShumwayCom.jsm#L574)):</sup>
I turned it into

    try {
      var baseURI = Services.io.newURI(this.baseUrl, null, null);
      var scheme = Services.io.newURI(url, null, baseURI).scheme;
    } catch (e) {
      log("Warning, attempt to navigate to invalid URI '" + url + "'");
      return;
    }
in the end.

---

<sup>**[extension/firefox/chrome/ShumwayCom.jsm, line 575 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2349#-JxgH7A3UPLKRnMTw_iG)** ([raw file](https://github.com/mozilla/shumway/blob/b27e1676b6cd0ba6dad60089c15189a00f9b3467/extension/firefox/chrome/ShumwayCom.jsm#L575)):</sup>
Whoa, thanks.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2349)

**Pull request merged**
