### PR TITLE
Don't synch stage and mouse target updates every frame.

### PR DESCRIPTION
**Pull request by mbebenita**
[Review on Reviewable](https://reviewable.io/reviews/mozilla/shumway/2354)

### CODE REVIEW

**Comment by tobytailor** [comment]
Reviewed 5 of 5 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2354)

**Comment by tobytailor** [comment]
Looks good, r+.

**Comment by tschneidereit** [comment]
Reverting the unconditional r+. r+ with comments addressed instead.

---

Reviewed 3 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[src/flash/display/Stage.ts, line 144 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2354#-JxpuimqWcS4nfoq_Lmv)** ([raw file](https://github.com/mozilla/shumway/blob/863faca5daddbd6fbcb448f2f8349ed9ff981c0e/src/flash/display/Stage.ts#L144)):</sup>
I guess I would've moved the assignment into the `if` block above for this and all the other changed things below. Not important, though.

---

<sup>**[src/flash/display/Stage.ts, line 346 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2354#-Jxpv7k_wq-xH86vv2tm)** ([raw file](https://github.com/mozilla/shumway/blob/863faca5daddbd6fbcb448f2f8349ed9ff981c0e/src/flash/display/Stage.ts#L346)):</sup>
Add a `var newValue = ` here like you did above.

---

<sup>**[src/player/remotingPlayer.ts, line 115 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2354#-JxpvpLoJUG2kqdgxRJ7)** ([raw file](https://github.com/mozilla/shumway/blob/863faca5daddbd6fbcb448f2f8349ed9ff981c0e/src/player/remotingPlayer.ts#L115)):</sup>
Change this to an early return instead of wrapping everything in the method into the block.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2354)

**Pull request merged**
