### PR TITLE
Bug 1150641 - Add Shumway telemetry probe for cross domain loading issues

### PR DESCRIPTION
**Pull request by yurydelendik**
r? @tschneidereit

[Review on Reviewable](https://reviewable.io/reviews/mozilla/shumway/2245)

### CODE REVIEW

**Comment by yurydelendik** [comment]
The probes "split" into two categories: loading swf and loading URLStream. For loading SWF we are reporting if SWF loading was rejected based on allowDomain whitelist. For loading via URLStream, we reporting if access was denied based on crossdomain.xml restrictions.

**Comment by tschneidereit** [comment]
Looks good with comments addressed. One thing is a bit weird, IMO, though: for loads the probe really just reports whether they where allowed to happen or not, but for streams it also reports on whether loading was successful or not. Perhaps that would be better in another probe? We should also have reporting for it in the Loader, after all.

---

Review status: all files reviewed, 11 unresolved discussions, all commit checks successful.
Reviewed files:
- extension/firefox/chrome/FileLoader.jsm @ r1
- extension/firefox/chrome/ShumwayCom.jsm @ r1
- extension/firefox/content/ShumwayTelemetry.jsm @ r1
- extension/mozcentral/browser/extensions/shumway/content/ShumwayTelemetry.jsm @ r1
- src/base/utilities.ts @ r1
- src/flash/display/Loader.ts @ r1
- src/flash/net/URLStream.ts @ r1
- src/flash/system/Security.ts @ r1
- src/player/external.ts @ r1
- src/player/settings.ts @ r1

---

<sup>**[src/base/utilities.ts, line 3492 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2245#-JqKXbx1XBncf7aR0OJn)** ([raw file](https://github.com/mozilla/shumway/blob/59bdea5a81cf0976ecd7e5097aa9c601fb902efc/src/base/utilities.ts#L3492)):</sup>
Nit: please use `CamelCasing` instead of `UPPERCASING` for enum entries.

---

<sup>**[src/base/utilities.ts, line 3494 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2245#-JqKpM9CzP9pETu5hLqe)** ([raw file](https://github.com/mozilla/shumway/blob/59bdea5a81cf0976ecd7e5097aa9c601fb902efc/src/base/utilities.ts#L3494)):</sup>
I'd prefer `Denied` and `Allowed` for both the load and the stream cases.

---

<sup>**[src/flash/display/Loader.ts, line 379 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2245#-JqKYNSK7R2F2ANoLE-1)** ([raw file](https://github.com/mozilla/shumway/blob/59bdea5a81cf0976ecd7e5097aa9c601fb902efc/src/flash/display/Loader.ts#L379)):</sup>
I would change this to `whitelistResult !== CrossDomainSWFLoadingWhitelistResult.Failed`.

---

<sup>**[src/flash/net/URLStream.ts, line 107 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2245#-JqKYgxtkExI1BG_dSye)** ([raw file](https://github.com/mozilla/shumway/blob/59bdea5a81cf0976ecd7e5097aa9c601fb902efc/src/flash/net/URLStream.ts#L107)):</sup>
Nit: please wrap this at 100 cols. Same below.

---

<sup>**[src/flash/system/Security.ts, line 111 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2245#-JqKXOvA1Wyfi60eI1vy)** ([raw file](https://github.com/mozilla/shumway/blob/59bdea5a81cf0976ecd7e5097aa9c601fb902efc/src/flash/system/Security.ts#L111)):</sup>
Nit: please use `CamelCasing` instead of `UPPERCASING` for enum entries.

---

<sup>**[src/flash/system/Security.ts, line 112 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2245#-JqKWvZ9Fvu6lmSCE_Ai)** ([raw file](https://github.com/mozilla/shumway/blob/59bdea5a81cf0976ecd7e5097aa9c601fb902efc/src/flash/system/Security.ts#L112)):</sup>
Nit: please use line comments here and below. These won't be picked up by doc comment tools anyway, I think. If I'm wrong and they are picked up, ignore this.

---

<sup>**[src/flash/system/Security.ts, line 113 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2245#-JqKX6Pd7E1jwSv7KDrl)** ([raw file](https://github.com/mozilla/shumway/blob/59bdea5a81cf0976ecd7e5097aa9c601fb902efc/src/flash/system/Security.ts#L113)):</sup>
I'd prefer a different name for this. I had to go here to understand the code using it because I didn't get that it meant the using SWF's domain. `OwnDomain` would work for me.

---

<sup>**[src/player/settings.ts, line 768 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2245#-JqKnHD3nO_MJn7hf76p)** ([raw file](https://github.com/mozilla/shumway/blob/59bdea5a81cf0976ecd7e5097aa9c601fb902efc/src/player/settings.ts#L768)):</sup>
Please add a type definition or even a class for this. Also, please rename `source` to something like `ownDomain` for the same reasons given for the enum entry.

---

<sup>**[src/player/settings.ts, line 770 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2245#-JqKnh-gqXrMmgx7e86O)** ([raw file](https://github.com/mozilla/shumway/blob/59bdea5a81cf0976ecd7e5097aa9c601fb902efc/src/player/settings.ts#L770)):</sup>
Why is the new parameter optional? The two existing call sites should, IMO, clearly communicate the type of entry added here.

---

<sup>**[src/player/settings.ts, line 797 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2245#-JqKohjgw22V8wdV2gHn)** ([raw file](https://github.com/mozilla/shumway/blob/59bdea5a81cf0976ecd7e5097aa9c601fb902efc/src/player/settings.ts#L797)):</sup>
Can't the two `else` blocks be simplified to `else { success = entry.insecure || url.protocol === entry.protocol; }`?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2245)

**Comment by yurydelendik** [comment]
Review status: 5 of 10 files reviewed, 3 unresolved discussions, some commit checks pending.

---

<sup>**[src/flash/system/Security.ts, line 112 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2245#-JqKWvZ9Fvu6lmSCE_Ai)** ([raw file](https://github.com/mozilla/shumway/blob/59bdea5a81cf0976ecd7e5097aa9c601fb902efc/src/flash/system/Security.ts#L112)):</sup>
no preference here, fixed

---

<sup>**[src/player/settings.ts, line 797 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2245#-JqKohjgw22V8wdV2gHn)** ([raw file](https://github.com/mozilla/shumway/blob/59bdea5a81cf0976ecd7e5097aa9c601fb902efc/src/player/settings.ts#L797)):</sup>
out of scope of this PR

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2245)

**Comment by yurydelendik** [comment]
Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- extension/firefox/chrome/FileLoader.jsm @ r1
- extension/firefox/chrome/ShumwayCom.jsm @ r1
- extension/firefox/content/ShumwayTelemetry.jsm @ r1
- extension/mozcentral/browser/extensions/shumway/content/ShumwayTelemetry.jsm @ r1
- src/base/utilities.ts @ r2
- src/flash/display/Loader.ts @ r2
- src/flash/net/URLStream.ts @ r2
- src/flash/system/Security.ts @ r2
- src/player/external.ts @ r1
- src/player/settings.ts @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2245)

**Comment by yurydelendik** [comment]
Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/flash/system/Security.ts, line 112 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2245#-JqKWvZ9Fvu6lmSCE_Ai)** ([raw file](https://github.com/mozilla/shumway/blob/59bdea5a81cf0976ecd7e5097aa9c601fb902efc/src/flash/system/Security.ts#L112)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2245)

**Pull request merged**
