### PR TITLE
Bug 1171168 - Fix string coercion in AVM1's TextField text and htmlText setters

### PR DESCRIPTION
**Pull request by tschneidereit**
[Review on Reviewable](https://reviewable.io/reviews/mozilla/shumway/2271)

### CODE REVIEW

**Comment by yurydelendik** [comment]
Review status: all files reviewed, all discussions resolved.
Reviewed files:
- src/avm1/runtime.ts @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2271)

**Comment by tschneidereit** [comment]
Reviewable.io sadly doesn't show all changes in this PR. I opened [an issue](https://github.com/Reviewable/Reviewable/issues/108) about that.

**Comment by yurydelendik** [comment]
Looks good.

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- src/avm1/lib/AVM1TextField.ts @ r2
- src/avm1/runtime.ts @ r1
- test/swfs/avm1/textfield-html/textfield-html.fla @ r2
- test/swfs/avm1/textfield-html/textfield-html.swf @ r2
- test/swfs/avm1/textfield-html/textfield-html.swf.trace @ r2
- test/swfs/avm1/textfield/textfield-html.fla @ r2
- test/swfs/avm1/textfield/textfield-html.swf @ r2
- test/swfs/avm1/textfield/textfield-html.swf.trace @ r2
- test/swfs/avm1/textfield/textfield-text-setters.fla @ r2
- test/swfs/avm1/textfield/textfield-text-setters.swf @ r2
- test/swfs/avm1/textfield/textfield-text-setters.swf.trace @ r2
- test/test_manifest_trace.json @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2271)

**Pull request merged**
