### PR TITLE
Bug 1125489 - Fixes compiling of the switch with case containing if.

### PR DESCRIPTION
**Pull request by yurydelendik**
https://bugzilla.mozilla.org/show_bug.cgi?id=1125489

### CODE REVIEW

**Comment by mbebenita** [comment]
You're a hero. :+1:

**Comment by ananyaojha** [comment]
I want to call a func immediately after the pdf loading in the viewer. How to get that location?

**Comment by ananyaojha** [comment]
I need help regarding pdfjs. I commented thee too. BT nobody replied till now

**Comment by yurydelendik** [comment]
> I need help regarding pdfjs. I commented thee too. BT nobody replied till now

@ananyaojha wrong place. See https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md to properly engage the project contributors.

**Pull request merged**
