### PR TITLE
Optimize lookup of _levelN, _root, and well-known MovieClip properties in AVM1

### PR DESCRIPTION
**Pull request by tschneidereit**
r? @yurydelendik

[Review on Reviewable](https://reviewable.io/reviews/mozilla/shumway/2345)

### CODE REVIEW

**Comment by tschneidereit** [comment]
I wish just including "r? someone" in a message would change the assignee.

**Comment by tobytailor** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2345)

**Comment by tobytailor** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2345)

**Pull request merged**
