### PR TITLE
Bug 1171898 - Box call arguments in ExternalInterface before invoking registered callbacks

### PR DESCRIPTION
**Pull request by tschneidereit**
r? @yurydelendik

[Review on Reviewable](https://reviewable.io/reviews/mozilla/shumway/2274)

### CODE REVIEW

**Comment by tschneidereit** [comment]
Review ping.

**Comment by yurydelendik** [comment]
Looks good

---

Review status: 0 of 1 files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/flash/external/ExternalInterface.ts, line 89 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2274#-JrT8agKNHqOAhyhN8CH)** ([raw file](https://github.com/mozilla/shumway/blob/68f34e03c96bf44340fa2f985ba85d4fb193731c/src/flash/external/ExternalInterface.ts#L89)):</sup>
(I don't think it would be a case here but) can you compare for not-null using `arg !== null` to avoid potential valueOf call.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2274)

**Comment by yurydelendik** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- src/flash/external/ExternalInterface.ts @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2274)

**Comment by yurydelendik** [comment]
Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/flash/external/ExternalInterface.ts, line 84 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2274#-JrTAQMohDrU3CyotQwQ)** ([raw file](https://github.com/mozilla/shumway/blob/68f34e03c96bf44340fa2f985ba85d4fb193731c/src/flash/external/ExternalInterface.ts#L84)):</sup>
on second thought, also keep this as `(args != null)`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2274)

**Comment by tschneidereit** [comment]
Thanks for the review. I opted not to make the changes you requested, for the reasons given below.

---

Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[src/flash/external/ExternalInterface.ts, line 84 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2274#-JrTAQMohDrU3CyotQwQ)** ([raw file](https://github.com/mozilla/shumway/blob/68f34e03c96bf44340fa2f985ba85d4fb193731c/src/flash/external/ExternalInterface.ts#L84)):</sup>
Same as for the other check: a `valueOf` call can't happen here, making the check equivalent with what you propose for all intents and purposes.

---

<sup>**[src/flash/external/ExternalInterface.ts, line 89 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2274#-JrT8agKNHqOAhyhN8CH)** ([raw file](https://github.com/mozilla/shumway/blob/68f34e03c96bf44340fa2f985ba85d4fb193731c/src/flash/external/ExternalInterface.ts#L89)):</sup>
A `valueOf` can't happen here: objects are always truthy, without any further checks. (The only exception is `document.all`, but that doesn't apply here, obviously.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2274)

**Pull request merged**
