### PR TITLE
Factor most state from _interpret into InterpreterFrame instance

### PR DESCRIPTION
**Pull request by tschneidereit**
Four reasons for doing this:
 - It's easier to follow.
 - It makes debugging easier because it makes it trivial to skip over the setup of all this state instead of having to single-step through it.
 - It's very slightly faster (~5% by my rough measurements).
 - It paves the way for extracting rarely used bytecodes into a new function to make the main interpreter loop much lighter-weight and better optimizable.

 But really, the first two are the motivation.

### CODE REVIEW

**Comment by tschneidereit** [comment]
@mbebenita, please take a look. If you don't like it at all, I'll can it. It does help me with debugging, though.

**Comment by mbebenita** [comment]
> It paves the way for extracting rarely used bytecodes into a new function to make the main interpreter loop much lighter-weight and better optimizable.

Another advantage is that it would make it easier to reuse the same `_interpreter` JS frame, for multiple AS frames.

**Comment by mbebenita** [comment]
r+, I'm fine with the approach.

**Comment by tschneidereit** [comment]
> Ah, but having local and stack be the same number of chars used to be so nice. But, I'll live with it :)

But the grammar! Think of the poor children who might read our source code and be led on dark, dark path!

**Pull request merged**
