### PR TITLE
AVM1: Optimize name normalization

### PR DESCRIPTION
**Pull request by tschneidereit**
r? @yurydelendik

[Review on Reviewable](https://reviewable.io/reviews/mozilla/shumway/2364)

### CODE REVIEW

**Comment by tschneidereit** [comment]
Depends on #2363 and #2337.

**Comment by yurydelendik** [comment]
Looks good. r=me with assignment statement fixed.

Thank you for the patch.

---

Reviewed 1 of 1 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/avm1/context.ts, line 145 \[r2\]](https://reviewable.io:443/reviews/mozilla/shumway/2364#-JyojAVnyBLk5eHj8bHi)** ([raw file](https://github.com/mozilla/shumway/blob/34378644507a29735a4d5956ebf88edfb4728b05/src/avm1/context.ts#L145)):</sup>
Move the assignment to the previous line.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2364)

**Pull request merged**
