### PR TITLE
Bug 1160230 - Sandboxing gfx window

### PR DESCRIPTION
**Pull request by yurydelendik**
https://bugzilla.mozilla.org/show_bug.cgi?id=1160230

[Review on Reviewable](https://reviewable.io/reviews/mozilla/shumway/2249)

### CODE REVIEW

**Comment by tschneidereit** [comment]
This is a really nice change! I especially like the factoring out of the messaging into the peering objects. I added a few comments, but they're all minor or cosmetic, so r=me with them addressed.

---

Review status: all files reviewed, 14 unresolved discussions, all commit checks successful.
Reviewed files:
- examples/inspector/js/inspectorGfx.js @ r1
- examples/inspector/js/inspectorPlayer.js @ r1
- extension/firefox/chrome/ShumwayCom.jsm @ r1
- extension/firefox/content/web/viewer.html @ r1
- extension/firefox/content/web/viewer.js @ r1
- extension/firefox/content/web/viewerGfx.js @ r1
- extension/firefox/content/web/viewerPlayer.js @ r1
- src/base/external.ts @ r1
- src/base/remoting.ts @ r1
- src/gfx/test/recordingEaselHost.ts @ r1
- src/gfx/window/windowEaselHost.ts @ r1
- src/player/window/windowPlayer.ts @ r1
- test/harness/slaveGfx.js @ r1
- test/harness/slavePlayer.js @ r1
- web/iframe/viewerGfx.js @ r1
- web/iframe/viewerPlayer.js @ r1

---

<sup>**[extension/firefox/chrome/ShumwayCom.jsm, line 167 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2249#-JqOkKtNdmive5R4ySTS)** ([raw file](https://github.com/mozilla/shumway/blob/504556464dde4af5b415e98c6754c394ad043ee5/extension/firefox/chrome/ShumwayCom.jsm#L167)):</sup>
s/Brodge/Bridge/. But really, I'd also be fine with replacing all of this with short method definitions: 
`..}, setupGfxComBridge(gfxWindow) {..}, ..`
If you don't agree with using ES6 stuff here, at least you can just drop the name duplication: the name for the function is inferred from the field name it is assigned to. (For ES6 this is even standardized, but SpiderMonkey has done it for quite some time.)

---

<sup>**[extension/firefox/chrome/ShumwayCom.jsm, line 168 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2249#-JqKSM28QHX_uSSkhwAQ)** ([raw file](https://github.com/mozilla/shumway/blob/504556464dde4af5b415e98c6754c394ad043ee5/extension/firefox/chrome/ShumwayCom.jsm#L168)):</sup>
Can you change this comment to be a bit more specific than "secondary"? What does that mean in practice? Same below. (Yes I know: preexisting, but would still be nice to have a comment.)

---

<sup>**[extension/firefox/chrome/ShumwayCom.jsm, line 169 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2249#-JqKSndE_1ohsNxbVXAm)** ([raw file](https://github.com/mozilla/shumway/blob/504556464dde4af5b415e98c6754c394ad043ee5/extension/firefox/chrome/ShumwayCom.jsm#L169)):</sup>
Please add a comment explaining why the object needs to be unwrapped here. (And below.)

---

<sup>**[extension/firefox/chrome/ShumwayCom.jsm, line 209 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2249#-JqOljg7IiTAPy8R2Mkj)** ([raw file](https://github.com/mozilla/shumway/blob/504556464dde4af5b415e98c6754c394ad043ee5/extension/firefox/chrome/ShumwayCom.jsm#L209)):</sup>
Do we ever replace these hooks? I.e. is it ever valid to reset one of them to `null`? If not, perhaps emit an error to the console?

---

<sup>**[extension/firefox/chrome/ShumwayCom.jsm, line 213 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2249#-JqOluAtqsXlwWNZF1St)** ([raw file](https://github.com/mozilla/shumway/blob/504556464dde4af5b415e98c6754c394ad043ee5/extension/firefox/chrome/ShumwayCom.jsm#L213)):</sup>
This check should never fail, right? Perhaps replace it with
`if (typeof callback !== 'function') {
    log('error: attempt to set non-callable as callback in setSyncMessageCallback');
    return;
}`
Same for the other callbacks, of course. Would sure be nice to have asserts in this code ...

---

<sup>**[extension/firefox/content/web/viewer.js, line 99 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2249#-JqOsRCJColNPadlw77O)** ([raw file](https://github.com/mozilla/shumway/blob/504556464dde4af5b415e98c6754c394ad043ee5/extension/firefox/content/web/viewer.js#L99)):</sup>
Don't we need to sanitize `args.params` here? We trust the gfx iframe slightly more than the player iframe, but not fully.

---

<sup>**[extension/firefox/content/web/viewer.js, line 119 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2249#-JqOtVoLQ0L0xxkMERzk)** ([raw file](https://github.com/mozilla/shumway/blob/504556464dde4af5b415e98c6754c394ad043ee5/extension/firefox/content/web/viewer.js#L119)):</sup>
Can you add a default case that logs an error?

---

<sup>**[extension/firefox/content/web/viewer.js, line 183 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2249#-JqOspsDmr6lJJByQk9h)** ([raw file](https://github.com/mozilla/shumway/blob/504556464dde4af5b415e98c6754c394ad043ee5/extension/firefox/content/web/viewer.js#L183)):</sup>
Preexisting, but should we only log these in debug mode?

---

<sup>**[extension/firefox/content/web/viewer.js, line 207 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2249#-JqOsgiLEe8qXM4EX8an)** ([raw file](https://github.com/mozilla/shumway/blob/504556464dde4af5b415e98c6754c394ad043ee5/extension/firefox/content/web/viewer.js#L207)):</sup>
Please add a comment explaining what's going on here.

---

<sup>**[extension/firefox/content/web/viewerGfx.js, line 110 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2249#-JqOtPjsfzIw8x6tme9d)** ([raw file](https://github.com/mozilla/shumway/blob/504556464dde4af5b415e98c6754c394ad043ee5/extension/firefox/content/web/viewerGfx.js#L110)):</sup>
Please log an error here: this really shouldn't happen.

---

<sup>**[src/base/remoting.ts, line 224 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2249#-JqOtn6nMdkoBrXADAq-)** ([raw file](https://github.com/mozilla/shumway/blob/504556464dde4af5b415e98c6754c394ad043ee5/src/base/remoting.ts#L224)):</sup>
Please add a short comment explaining what this is for. It's non-trivial and not really self-explanatory.

---

<sup>**[src/base/remoting.ts, line 248 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2249#-JqOuOOxj0g4y2CDZL3p)** ([raw file](https://github.com/mozilla/shumway/blob/504556464dde4af5b415e98c6754c394ad043ee5/src/base/remoting.ts#L248)):</sup>
I think I'd prefer `target` over `other`.

---

<sup>**[src/gfx/test/recordingEaselHost.ts, line 34 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2249#-JqOv-tl_t7eabf_9slr)** ([raw file](https://github.com/mozilla/shumway/blob/504556464dde4af5b415e98c6754c394ad043ee5/src/gfx/test/recordingEaselHost.ts#L34)):</sup>
Can we turn this into an assert? Or is there ever a valid reason for this condition to be true?

---

<sup>**[src/gfx/window/windowEaselHost.ts, line 107 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2249#-JqOvbtFkHmXgbXCkAKe)** ([raw file](https://github.com/mozilla/shumway/blob/504556464dde4af5b415e98c6754c394ad043ee5/src/gfx/window/windowEaselHost.ts#L107)):</sup>
Can we re-enable this assert?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2249)

**Comment by yurydelendik** [comment]
Review status: all files reviewed, 10 unresolved discussions, all commit checks successful.

---

<sup>**[extension/firefox/content/web/viewer.js, line 99 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2249#-JqOsRCJColNPadlw77O)** ([raw file](https://github.com/mozilla/shumway/blob/504556464dde4af5b415e98c6754c394ad043ee5/extension/firefox/content/web/viewer.js#L99)):</sup>
Sanitize how? it's coming via window postMessage, I don't expect any bad input to feed it back to the player iframe back.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2249)

**Comment by yurydelendik** [comment]
Review status: all files reviewed, 8 unresolved discussions, all commit checks successful.

---

<sup>**[extension/firefox/content/web/viewer.js, line 183 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2249#-JqOspsDmr6lJJByQk9h)** ([raw file](https://github.com/mozilla/shumway/blob/504556464dde4af5b415e98c6754c394ad043ee5/extension/firefox/content/web/viewer.js#L183)):</sup>
Debug info removed

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2249)

**Comment by yurydelendik** [comment]
Review status: all files reviewed, 4 unresolved discussions, all commit checks successful.

---

<sup>**[src/gfx/window/windowEaselHost.ts, line 107 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2249#-JqOvbtFkHmXgbXCkAKe)** ([raw file](https://github.com/mozilla/shumway/blob/504556464dde4af5b415e98c6754c394ad043ee5/src/gfx/window/windowEaselHost.ts#L107)):</sup>
That's was disabled for non-iframe inspector. If we are not planing to use gfx and player in one window/frame, I can remove that.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2249)

**Comment by tschneidereit** [comment]
Sorry, I didn't see the follow-up - bad mail reading on my part :(

Thanks for addressing the feedback, this all looks splendid.

---

Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- extension/firefox/chrome/ShumwayCom.jsm @ r2
- extension/firefox/content/web/viewer.js @ r2
- extension/firefox/content/web/viewerGfx.js @ r2
- extension/firefox/content/web/viewerPlayer.js @ r2
- src/base/remoting.ts @ r2
- src/gfx/test/recordingEaselHost.ts @ r2

---

<sup>**[extension/firefox/content/web/viewer.js, line 99 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2249#-JqOsRCJColNPadlw77O)** ([raw file](https://github.com/mozilla/shumway/blob/504556464dde4af5b415e98c6754c394ad043ee5/extension/firefox/content/web/viewer.js#L99)):</sup>
Right, ignore this. We should trust the outside world in the viewer - nothing else makes sense.

---

<sup>**[src/gfx/window/windowEaselHost.ts, line 107 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2249#-JqOvbtFkHmXgbXCkAKe)** ([raw file](https://github.com/mozilla/shumway/blob/504556464dde4af5b415e98c6754c394ad043ee5/src/gfx/window/windowEaselHost.ts#L107)):</sup>
Can you explain how that affects this assert? Why would we encounter unhandled events here in the single-global case?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2249)

**Comment by yurydelendik** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/gfx/window/windowEaselHost.ts, line 107 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2249#-JqOvbtFkHmXgbXCkAKe)** ([raw file](https://github.com/mozilla/shumway/blob/504556464dde4af5b415e98c6754c394ad043ee5/src/gfx/window/windowEaselHost.ts#L107)):</sup>
e.g. gfx sends updates messages at https://github.com/mozilla/shumway/blob/master/src/gfx/window/windowEaselHost.ts#L52 and player requests updates at https://github.com/mozilla/shumway/blob/master/src/player/window/windowPlayer.ts#L48. Both gfx and player use postMessage and if this._parent === this._playerWindow the asserts will fail.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2249)

**Comment by tschneidereit** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/gfx/window/windowEaselHost.ts, line 107 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2249#-JqOvbtFkHmXgbXCkAKe)** ([raw file](https://github.com/mozilla/shumway/blob/504556464dde4af5b415e98c6754c394ad043ee5/src/gfx/window/windowEaselHost.ts#L107)):</sup>
Ah! And how about changing the `else` to `else if (this._parent !== this._playerWindow)`, then? I like asserts and want them not-gone :)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2249)

**Comment by yurydelendik** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/gfx/window/windowEaselHost.ts, line 107 \[r1\]](https://reviewable.io:443/reviews/mozilla/shumway/2249#-JqOvbtFkHmXgbXCkAKe)** ([raw file](https://github.com/mozilla/shumway/blob/504556464dde4af5b415e98c6754c394ad043ee5/src/gfx/window/windowEaselHost.ts#L107)):</sup>
Oh, 'this'es above belong to different objects EaselHost and Player. So it's not just this._parent !== this._playerWindow comparison. I'll keep this change/issue out of this PR for now -- it's not related to the subject.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mozilla/shumway/2249)

**Pull request merged**
